on: [push]

jobs:
  autograde_job:
    runs-on: ubuntu-latest
    name: alem js autograde
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Autograde action
        uses: alem-classroom/js-autograde@v1
        id: hello2
        with:
          grade: ${{ secrets.GRADE }}
          url: 'alem-classroom/test-js-intro'
          token: ${{ secrets.AUTH_TOKEN }}
